Add : 전체 티 상품 페이지 및 URL
wecode-bootcamp-korea/11-t2gether-backend pull request #4
Opened 2020-08-24 09:38 UTC by danielgyu

- 전체 상품 페이지 뷰

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-08-26 05:08 UTC, soheon-lee commented on product/views.py
> +                    'product__refine__name', 'product__refine__category').distinct())
`list`에 내용을 추가하실 때에는 `+=` 보다 `append( )` 메소드를 활용하시는 것을 추천드립니다.
그것 보다, 두 조건이 `or`인가요? django에서는 이런 경우에 사용하기에 좋은 `Q `라는 방법이 있습니다. 한 번 활용해보세요 :)

2020-08-26 05:08 UTC, soheon-lee commented on product/views.py
> +            tea_products = Product.objects.filter(refine__name__in = styles).filter(refine__name__in = teas)
필터뷰를 AllTeaView와 같이 합치시느라 고생하셨습니다 👍 
이러한 경우 필터링 조건이 하나 더 늘어나면 어떻게 될까요..? 아마 if 문이 두배로 늘어나게 될 것 입니다.
styles라는 조건이 들어올 수도 있고 들어오지 않을 수도 있고, teas라는 조건이 또 들어올 수도 있고, 들어오지 않을 수도 있죠?
이렇게 필터링할 조건이 optional할 경우에 어떻게 최적화할 수 있을 지 조금 더 고민해보셔야 할 것 같습니다.

hint) how to filter data with optional conditions in django ?

2020-08-26 05:39 UTC, danielgyu commented on product/views.py
> +                    'product__refine__name', 'product__refine__category').distinct())
style에 해당되는 필터들만 적용됐을 경우 style안에서 합집합이고,
tea에 해당되는 필터들만 적용됐을 경우에는 tea안에서 합집합이고,
style과 tea에 필터 적용이 안되면 전체를 보여주고,
style과 tea에 해당되는 필터들이 적용됐을 경우에는 교집합이라서 저렇게 나눠놨습니다~~
Q를 사용해서 or를 하면 둘다 있을 경우 두개의 합집합이 되는거 같아서..

2020-08-26 11:42 UTC, lordmyshepherd requested changes

2020-08-26 11:42 UTC, lordmyshepherd commented on product/views.py
> +                    'product__refine__name', 'product__refine__category').distinct())
42 - 54를 아래 방법을 추천드립니다!
```
q = Q()
if styles:
    q &= Q(refine__name__in = styles)
if teas:
    q &= Q(refine__name__in = teas)

products = Filter.objects.filter(q).values(...)
```

2020-08-27 04:40 UTC, soheon-lee commented
LGTM

2020-08-27 04:40 UTC, merged